/* auto-generated by NAPI-RS */
/* eslint-disable */
/** 音频播放器，通过 napi-rs 暴露给 Node.js */
export declare class AudioPlayer {
  /** 创建新的播放器实例 */
  constructor()
  /**
   * 重新初始化音频输出设备（系统休眠唤醒、设备热插拔或输出流错误后调用）
   *
   * 恢复为全成全败：新输出创建失败时不启动解码、不提交状态，保留当前曲目与位置，
   * 播放器进入暂停态并返回设备错误；在线音源不会因设备错误触发 URL 重取或 sourceError。
   */
  reinitOutput(): Promise<void>
  /** 设置封面缓存目录（在 load 前调用一次即可） */
  setCoverCacheDir(dir: string): void
  /** 注册事件回调，Rust 侧会在状态变化、位置更新、播放结束时主动调用 */
  onEvent(callback: (event: JsPlayerEvent) => void): void
  /** 当前平台是否支持原生音频设备监听 */
  supportsDeviceWatcher(): boolean
  /**
   * 注册系统音频设备变化回调，不支持的平台由主进程轮询
   * 回调参数为 true 表示默认输出设备切换，false 表示设备列表变化
   */
  onDeviceChange(callback: (defaultChanged: boolean) => void): void
  /** 停止系统音频设备变化监听 */
  stopDeviceWatcher(): void
  /**
   * 加载音频源，返回完整元信息（含封面路径和歌词）
   * @param auto_play - 是否自动播放，false 时加载后立即暂停
   *
   * 异步三段式：
   * 1. 主线程持锁瞬间（微秒级）：take 旧解码线程 handle + 拿参数（cover_dir / 归一化开关）
   * 2. spawn_blocking 工作线程（**不持有 inner 引用**）：读取音源采样率、协商输出流并启动解码
   * 3. 主线程持锁瞬间：提交输出流、构造 sink + attach + emit stateChanged
   * 持锁阶段都是纯内存操作，主线程其它同步 NAPI 调用最多等几微秒，不会被 IO 卡住
   */
  load(source: string, autoPlay?: boolean): Promise<JsMusicMetadata>
  /** 恢复播放。如果已停止或播放结束，自动从头重新加载 */
  play(): Promise<void>
  /** 暂停播放 */
  pause(): void
  /** 立即暂停播放，用于输出设备切换前阻止短暂串音 */
  pauseImmediately(): void
  /** 停止播放并释放资源 */
  stop(): void
  /**
   * 跳转到指定播放位置（秒）
   *
   * 异步三段式：与 load 同样的设计原则
   * 1. 主线程瞬时持锁：take 旧解码线程 + 拿归一化参数
   * 2. 工作线程：join 旧线程 → ffmpeg seek → resume_decode 启动新解码线程
   * 3. 主线程瞬时持锁：attach 新 sink + emit 状态
   * seek 失败时 fallback 到完整 load
   */
  seek(position: number): Promise<void>
  /** 设置音量（0.0 ~ 1.0） */
  setVolume(volume: number): void
  /** 获取当前音量（0.0 ~ 1.0） */
  getVolume(): number
  /** 设置暂停/恢复时的渐变时长（毫秒），0 表示禁用渐变 */
  setFadeDuration(durationMs: number): void
  /** 获取当前渐变时长（毫秒） */
  getFadeDuration(): number
  /** 获取当前播放位置（秒） */
  getPosition(): number
  /** 获取总时长（秒） */
  getDuration(): number
  /** 获取当前播放状态快照 */
  getStatus(): JsPlayerStatus
  /** 启用/禁用 FFT 频谱推送（前端需要显示频谱时启用，不显示时禁用以节省性能） */
  setFftEnabled(enabled: boolean): void
  /** 获取 FFT 推送开关状态 */
  getFftEnabled(): boolean
  /** 启用/禁用音量归一化（实时响度均衡） */
  setNormalizationEnabled(enabled: boolean): void
  /** 获取音量归一化开关状态 */
  getNormalizationEnabled(): boolean
  /** 启用/禁用 10 频段均衡器 */
  setEqualizerEnabled(enabled: boolean): void
  /** 获取均衡器开关状态 */
  getEqualizerEnabled(): boolean
  /** 更新均衡器各频段增益（dB），长度必须为 10，范围 [-15, 15] */
  setEqualizerBands(gainsDb: Array<number>): void
  /** 获取均衡器各频段当前增益（dB） */
  getEqualizerBands(): Array<number>
  /** 设置前级增益（dB），范围 [-12, 12] */
  setPreampGain(preampDb: number): void
  /** 获取前级增益（dB） */
  getPreampGain(): number
  /** 获取 FFT 频谱数据（128 个频段，值域 0.0 ~ 1.0） */
  getFftData(): JsFftData
  /**
   * 返回 load 时缓存的原始封面数据（用于 SMTC / 全屏播放器）。
   * 封面在 load 阶段从已打开的 FFmpeg 上下文一次性提取，不再重复打开文件。
   */
  getCoverRaw(): Buffer | null
  /** 获取所有音频输出设备列表 */
  getOutputDevices(): Array<JsAudioDevice>
  /** 获取系统默认输出设备名称 */
  getDefaultDeviceName(): string | null
  /** 获取系统默认输出设备稳定 ID */
  getDefaultDeviceId(): string | null
  /** 切换输出设备（传设备 ID，None/undefined 使用系统默认） */
  setOutputDevice(deviceId?: string | undefined | null): Promise<void>
  /**
   * 获取当前选择的输出设备 ID（None = 跟随系统默认）
   *
   * 旧配置存的是显示名，此处原样返回，由 `open_device` 回退解析
   */
  getSelectedDeviceName(): string | null
  /** 设置播放速度（自动 clamp 到 [0.5, 2.0]） */
  setSpeed(speed: number): void
  /** 设置音调偏移（半音，自动 clamp 到 [-12, 12]） */
  setPitch(semitones: number): void
  /** 设置"音调同步"开关（true = 变速保音调） */
  setPitchSync(sync: boolean): void
  /** 获取当前播放速度 */
  getSpeed(): number
  /** 获取当前音调（半音） */
  getPitch(): number
  /** 获取"音调同步"开关状态 */
  getPitchSync(): boolean
}

/** 取消正在进行的扫描任务 */
export declare function cancelScan(): void

/** 已有文件记录，用于增量扫描比对 */
export interface FileRecord {
  path: string
  mtime: number
  size: number
}

/** 初始化原生日志系统。重复调用是无害的（HMR 重载时主进程可能多次注入） */
export declare function initLogger(logDir: string, isDev: boolean): void

/** 音频输出设备信息 */
export interface JsAudioDevice {
  /** 稳定设备 ID（cpal `DeviceId` 的字符串形式） */
  id: string
  /** 显示名 */
  name: string
  /** 是否为系统默认设备 */
  isDefault: boolean
}

/** 一条外部歌词，返回给 JS 侧（仅格式和路径，内容按需加载） */
export interface JsExternalLyric {
  /** 格式（如 "lrc", "ttml", "yrc", "qrc"） */
  format: string
  /** 文件路径 */
  path: string
}

/** FFT 双声道频谱数据 */
export interface JsFftData {
  ldata: Array<number>
  rdata: Array<number>
}

/** 歌曲完整元信息，返回给 JS 侧（load 时一次性返回） */
export interface JsMusicMetadata {
  title?: string
  artist?: string
  album?: string
  /** 注释/副标题 */
  comment?: string
  /** 时长（秒） */
  duration: number
  /** 播放采样率（重采样后） */
  sampleRate: number
  /** 声道数 */
  channels: number
  /** 原始采样率（解码前，用于音质显示） */
  originalSampleRate: number
  /** 位深（bits per sample） */
  bitsPerSample: number
  /** 比特率（bps） */
  bitRate: number
  /** 编码格式（如 "flac", "mp3", "aac"） */
  codec: string
  /** 内嵌歌词（从音频文件 tag 中读取） */
  embeddedLyric?: string
  /** 同目录下找到的所有歌词文件 */
  externalLyrics: Array<JsExternalLyric>
  /** 封面缩略图路径（300x300，用于前端日常显示） */
  cover?: string
}

/** 播放器事件，推送给 JS 侧 */
export interface JsPlayerEvent {
  /** 事件类型："stateChanged" | "ended" | "sourceError" | "position" | "fftData" | "outputStalled" | "outputFailed" */
  type: string
  /** 状态（仅 stateChanged 时有值） */
  state?: string
  /** 位置（秒，仅 position 时有值） */
  position?: number
  /** 时长（秒，仅 position 时有值） */
  duration?: number
  /** FFT 频谱数据（仅 fftData 时有值，128 个频段，值域 0.0 ~ 1.0） */
  fftData?: JsFftData
}

/** 播放器状态快照 */
export interface JsPlayerStatus {
  /** 播放状态："idle" | "playing" | "paused" | "stopped" */
  state: string
  /** 当前播放位置（秒） */
  position: number
  /** 总时长（秒） */
  duration: number
  /** 音量（0.0 ~ 1.0） */
  volume: number
  /** 是否已播放完毕 */
  isFinished: boolean
}

/** 扫描事件回调数据 */
export interface JsScanEvent {
  /** "progress" | "done" */
  eventType: string
  /** 已扫描文件数 */
  scanned: number
  /** 总文件数 */
  total: number
  /** 当前正在处理的文件名 */
  current?: string
  /** 本批次扫描结果 */
  tracks?: Array<JsScannedTrack>
  /** 已删除的文件路径列表（仅 done 事件） */
  removedPaths?: Array<string>
  /** 遍历时收集到的 CUE 文件路径（仅 done 事件） */
  cueFiles?: Array<string>
  /** 不可达的扫描目录 */
  unavailableDirs?: Array<string>
}

/** 扫描到的曲目信息 */
export interface JsScannedTrack {
  path: string
  title?: string
  artist?: string
  album?: string
  /** 音轨编号 */
  track?: number
  /** 时长（秒） */
  duration: number
  codec: string
  sampleRate: number
  bitRate: number
  channels: number
  bitsPerSample: number
  /** 封面缓存路径 */
  cover?: string
  /** 文件大小（字节） */
  fileSize: number
  /** 修改时间（Unix ms） */
  mtime: number
  /** 创建时间（Unix ms） */
  ctime: number
}

/**
 * 单文件标签写入请求。字段为 undefined/null 表示不修改；
 * 文本传空串、数字传 0 表示清除该标签项
 */
export interface JsTagWriteRequest {
  path: string
  title?: string
  artist?: string
  album?: string
  albumArtist?: string
  year?: number
  genre?: string
  trackNumber?: number
  discNumber?: number
  lyrics?: string
  /** 新封面图片数据（jpg/png），undefined 表示保留现有封面 */
  cover?: Buffer
}

/** 单文件写入结果 */
export interface JsTagWriteResult {
  path: string
  success: boolean
  error?: string
  /** 写入成功后重新探测的元数据 */
  track?: JsScannedTrack
}

/** 可编辑标签（读取结果） */
export interface JsTrackTags {
  title?: string
  artist?: string
  album?: string
  albumArtist?: string
  year?: number
  genre?: string
  trackNumber?: number
  discNumber?: number
  /** 内嵌歌词纯文本 */
  lyrics?: string
  /** 是否有内嵌封面 */
  hasCover: boolean
}

/**
 * 把任意图片字节缩成 JPEG 缩略图（用于选图预览）
 * 渲染层只拿小缩略图，避免整图解码成位图占用大量内存
 */
export declare function makeImageThumbnail(data: Buffer, maxSize: number): Promise<Buffer>

/** 读取文件的可编辑标签（异步，阻塞 IO 在 tokio 阻塞线程执行） */
export declare function readTrackTags(path: string): Promise<JsTrackTags>

/**
 * 批量扫描目录，通过回调推送进度和结果
 *
 * 在后台线程中执行，不阻塞 Node.js 事件循环。
 * 每处理约 20 个文件回调一次 progress 事件，完成后回调 done 事件。
 */
export declare function scanDirs(dirs: Array<string>, callback: (event: JsScanEvent) => void, coverCacheDir?: string | undefined | null, incrementalData?: Array<FileRecord> | undefined | null): void

/**
 * 批量写入标签（异步），逐项返回结果，单项失败不中断整批。
 * 替换封面时会作废旧缩略图缓存，写后按扫描同等规则重新生成
 */
export declare function writeTrackTags(requests: Array<JsTagWriteRequest>, coverCacheDir?: string | undefined | null): Promise<Array<JsTagWriteResult>>
