[package]
name = "taskbar-thumbnail"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { workspace = true, features = ["napi9"] }
napi-derive = { workspace = true }

[dependencies.windows]
workspace = true
features = [
  "Win32_Foundation",
  "Win32_Graphics_Dwm",
  "Win32_Graphics_Gdi",
  "Win32_UI_Shell",
  "Win32_UI_WindowsAndMessaging",
]

[build-dependencies]
napi-build = { workspace = true }

[lints]
workspace = true

