/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * 转换单个文本
 *
 * @param text - 待转换文本
 * @param config - OpenCC 配置名称 (如 "s2t", "t2s", "s2tw", "tw2s", "s2hk", "hk2s", "s2twp", "tw2sp", "t2tw", "tw2t", "t2hk", "hk2t", "jp2t", "t2jp")
 * @returns 转换后的文本
 */
export declare function convert(text: string, config: string): string

/**
 * 批量转换文本列表
 *
 * @param texts - 待转换文本数组
 * @param config - OpenCC 配置名称
 * @returns 转换后的文本数组
 */
export declare function convertBatch(texts: Array<string>, config: string): Array<string>

/** 获取所有支持的内置配置名称列表 */
export declare function getSupportedConfigs(): Array<string>
