/* auto-generated by NAPI-RS */
/* eslint-disable */
/** 一次采集会话 */
export declare class AudioCaptureSession {
  constructor()
  /** 当前平台是否支持本机采集 */
  isSupported(): boolean
  /** 开始采集 */
  start(config: JsCaptureConfig, callback: (event: JsCaptureEvent) => void): void
  /** 取消采集（可安全重复调用） */
  cancel(): void
}

export interface JsCaptureConfig {
  /** 采集来源："system"（系统声音）| "microphone" */
  source: string
  /** 最大采集时长（毫秒） */
  durationMs: number
}

export interface JsCaptureEvent {
  /** "level" | "done" | "error" */
  eventType: string
  /** 8 kHz 单声道 f32 LE 原始字节（仅 done 事件，cancelled 时为 None） */
  data?: Buffer
  /** 当前音量 RMS（level 事件） */
  level?: number
  /** 错误消息（error 事件） */
  error?: string
  /** 错误码："unsupported" | "no-device" | "permission-denied" | "capture-failed" */
  errorCode?: string
}
