[package]
name = "media-ctrl"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { workspace = true, features = ["tokio_rt", "napi9"] }
napi-derive = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync", "time"] }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }
time = { workspace = true }

# Discord RPC
discord-rich-presence = "1.0"
url = "2.5"

[build-dependencies]
napi-build = { workspace = true }

# Windows
[target.'cfg(target_os = "windows")'.dependencies.windows]
workspace = true
features = ["Media_Playback", "Storage_Streams", "Win32_System_Com"]

# Linux
[target.'cfg(target_os = "linux")'.dependencies]
mpris-server = "0.9"
tempfile = "3.24"

# macOS
[target.'cfg(target_os = "macos")'.dependencies]
block2 = "0.6"
objc2 = "0.6"
objc2-app-kit = "0.3"
objc2-foundation = "0.3"
objc2-media-player = "0.3"

[lints]
workspace = true
