/* auto-generated by NAPI-RS */
/* eslint-disable */
/** 禁用系统媒体控件 */
export declare function disable(): void

/** 禁用 Discord RPC */
export declare function disableDiscord(): void

export interface DiscordConfig {
  showWhenPaused: boolean
  displayMode?: DiscordDisplayMode
}

/** Discord 显示模式 */
export type DiscordDisplayMode = /** Listening to SPlayer */
'Name'|
/** Listening to {artist} */
'State'|
/** Listening to {title} */
'Details';

/** 启用系统媒体控件 */
export declare function enable(): void

/** 启用 Discord RPC */
export declare function enableDiscord(): void

/** 初始化系统媒体控件和 Discord RPC 后台线程 */
export declare function initialize(): void

/** 初始化原生日志系统（主进程启动时调用一次） */
export declare function initLogger(logDir: string, isDev: boolean): void

export interface MediaEvent {
  type: MediaEventType
  positionMs?: number
  rate?: number
  volume?: number
}

export type MediaEventType =  'Play'|
'Pause'|
'Stop'|
'NextTrack'|
'PrevTrack'|
'ToggleShuffle'|
'ToggleRepeat'|
'SetRate'|
'SetVolume'|
/** 绝对位置（毫秒） */
'Seek';

/** NAPI 层接收的元数据参数 */
export interface MetadataParam {
  title: string
  /** 歌手列表（MPRIS 需要多值，其余平台内部拼接） */
  artists: Array<string>
  album: string
  /** 封面原始字节（用于系统媒体控件） */
  coverData?: Buffer
  /** 封面 HTTP URL（用于 Discord RPC，Linux 无 cover_data 时也可用） */
  coverUrl?: string
  /** 时长（毫秒） */
  durationMs?: number
}

/** 注册媒体事件回调（播放/暂停/上一首/下一首等） */
export declare function onEvent(callback: (event: MediaEvent) => void): void

export type PlaybackStatus =  'Playing'|
'Paused';

export interface PlayModeParam {
  shuffle: boolean
  repeat: RepeatMode
}

export interface PlayStateParam {
  status: PlaybackStatus
}

export type RepeatMode =  'None'|
'Track'|
'List';

/** 更新 Discord RPC 配置 */
export declare function setDiscordConfig(config: DiscordConfig): void

/** 更新歌曲元数据（同时更新系统媒体控件和 Discord RPC） */
export declare function setMetadata(param: MetadataParam): void

/** 更新播放模式（随机/循环） */
export declare function setPlayMode(param: PlayModeParam): void

/** 更新播放状态 */
export declare function setPlayState(param: PlayStateParam): void

/** 更新播放速率 */
export declare function setRate(rate: number): void

/** 更新播放进度 */
export declare function setTimeline(param: TimelineParam): void

/** 更新音量 */
export declare function setVolume(volume: number): void

/** 关闭并清理资源 */
export declare function shutdown(): void

export interface TimelineParam {
  /** 当前位置（毫秒） */
  currentMs: number
  /** 总时长（毫秒） */
  totalMs: number
  /** 是否为 seek 操作触发 */
  seeked?: boolean
}
